In [3]:
import numpy as np

y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [4]:
# mean absolute error
def trad_mae(y_true, y_pred):
    total_error = 0
    for yt, yp in zip(y_true, y_pred):
        total_error += abs(yt-yp)
    print('total error is ',total_error)
    mae = total_error / len(y_true)
    print('mean absolute error is ',mae)
    return mae

In [5]:
trad_mae(y_true,y_pred)

total error is  2.5
mean absolute error is  0.5


0.5

In [6]:
print(np.abs(y_true-y_pred))
print(np.mean(np.abs(y_true-y_pred)))
# mean and abs operations using numpy

[0.7 0.3 1.  0.  0.5]
0.5


In [7]:
# with numpy
def mae(y_true, y_pred):
    return np.mean(np.abs(y_true-y_pred))

print('mean abs error is ',mae(y_true, y_pred))

mean abs error is  0.5


In [8]:
def trad_mse(y_true, y_pred):
    total_error = 0
    for yt, yp in zip(y_true, y_pred):
        total_error += abs(yt-yp)**2
    print('total error is ',total_error)
    trad_mse = total_error / len(y_true)
    return trad_mse

print("mean squared error is ",trad_mse(y_true, y_pred))

total error is  1.83
mean squared error is  0.366


In [9]:
def mse(y_true, y_pred):
    return np.mean(np.square(y_true-y_pred))
    
print("mean squared error is ",mse(y_true, y_pred))

mean squared error is  0.366


In [10]:
# binary cross entropy or Log loss
# log 1 is zero
# log 0 is inf
# therefore we have to take values which are close to 0 or 1

epsilon = 1e-15

y_pred_new = [max(i,epsilon) for i in y_pred]
y_pred_new = [min(i,1-epsilon)  for i in y_pred_new]
print('new --> ',y_pred_new)
print('old --> ',y_pred)

new -->  [0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]
old -->  [1 1 0 0 1]


In [11]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)
# log operation on array using numpy

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [12]:
BCE = -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
print(BCE)

17.2696280766844


In [13]:
# epsilon = 1e-15
def log_loss(y_true, y_pred):
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon)  for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    BCE = -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
    return BCE
    

In [14]:
log_loss(y_true,y_pred)

17.2696280766844

In [15]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))

In [16]:
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])