In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
# numpy broadcast
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
# dot product
units_rev = np.dot(price_per_unit,units)

In [10]:
units_rev*75

array([2580000, 3750000, 4830000])

In [13]:
Units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
pricePerUnitflower = np.array([20,30,15])

In [15]:
totalSalesInEveryMonth = np.dot(pricePerUnitflower,Units_sold)
totalSalesInEveryMonth

array([1900, 2640, 1430])